### ISSUE TITLE
Handy Converter

### ISSUE THREAD

**Issue by sideshot** [CaptainCodeman/svelte-transition#2]
The handy converter tool for the transitions is a 404 error page.

**Comment by dev2o** [comment]
Found the working link.

https://quick898.github.io/svelte-transition-converter/

**Comment by CaptainCodeman** [comment]
Thanks - updated!

**Comment by HamishWHC** [comment]
@CaptainCodeman the author changed their username (again?). New link seems to be: https://green-threads.github.io/svelte-transition-converter/

**Comment by CaptainCodeman** [comment]
Thanks! Link updated ...
